Ui testing with Selenium
xenony/python2019 pull request #3
Opened 2019-04-23 11:05 UTC by xenony

Add pageobject structure
Add selectors
Add base class and base methods
Add tests

2019-04-23 14:36 UTC, archick12 requested changes

2019-04-23 14:36 UTC, archick12 commented on pageobjects/issues_page.py
> +        time.sleep(5)
Please, replace sleep with WAIT.

2019-04-24 07:50 UTC, xenony commented on pageobjects/issues_page.py
> +        time.sleep(5)
Done

2019-04-24 08:13 UTC, archick12 approved these changes
Good Job!
Please, delete unused imports.

2019-04-24 08:14 UTC, merged